version: "3.8"

services:
  nexus:
    image: sonatype/nexus3
    ports:
      - 8081:8081
    volumes:
      - ./nexus-data:/nexus-data
    stdin_open: true
    tty: true

  nexus-webhook:
    image: python:buster
    command: "python /py/server.py"
    ports:
      - 8090:8090
    volumes:
      - ./py:/py
    stdin_open: true
    tty: true
